force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/Approval_Amend_Renwal_App_Data_Sync__mdt.object-meta.xml
<CustomObject>
    <label>Approval/Amend/Renwal App Data Sync</label>
    <pluralLabel>Approval/Amend/Renwal App Data Sync</pluralLabel>
</CustomObject>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Application_Specification_to_Consider__c.field-meta.xml
<CustomField>
    <fullName>Application_Specification_to_Consider__c</fullName>
    <description>List of Application Specification that we need to consider while cloning data to actual records</description>
    <label>Application Specification to Consider</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Child_Relationship_Field_Name_1__c.field-meta.xml
<CustomField>
    <fullName>Child_Relationship_Field_Name_1__c</fullName>
    <label>Child Relationship Field Name 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Child_Relationship_Field_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Child_Relationship_Field_Name_2__c</fullName>
    <label>Child Relationship Field Name 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Child_Relationship_Field_Name_3__c.field-meta.xml
<CustomField>
    <fullName>Child_Relationship_Field_Name_3__c</fullName>
    <label>Child Relationship Field Name 3</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Facility_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Facility_Application_Type__c</fullName>
    <label>Facility/Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Child Care Center</fullName>
                <default>true</default>
                <label>Child Care Center</label>
            </value>
            <value>
                <fullName>Group Home Child Care</fullName>
            </value>
            <value>
                <fullName>Family Home</fullName>
            </value>
            <value>
                <fullName>Friend, Family, Neighbor (FFN) Provider</fullName>
            </value>
            <value>
                <fullName>Relative Care Exempt (RCE) Provider</fullName>
            </value>
            <value>
                <fullName>School Age/ Drop In</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Flow_Type__c.field-meta.xml
<CustomField>
    <fullName>Flow_Type__c</fullName>
    <label>Flow Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <label>Parent Object</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Sync_Object_2__c.field-meta.xml
<CustomField>
    <fullName>Sync_Object_2__c</fullName>
    <label>Sync Object 2</label>
    <referenceTo>CC_DataSyncObjectMapping__mdt</referenceTo>
    <relationshipLabel>Approval/Amend/Renwal App Data Sync (Sync Objects 2)</relationshipLabel>
    <relationshipName>Approval_Amend_Renwal_App_Data_Sync1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Sync_Object_3__c.field-meta.xml
<CustomField>
    <fullName>Sync_Object_3__c</fullName>
    <label>Sync Object 3</label>
    <referenceTo>CC_DataSyncObjectMapping__mdt</referenceTo>
    <relationshipLabel>Approval/Amend/Renwal App Data Sync (Sync Object 3)</relationshipLabel>
    <relationshipName>Approval_Amend_Renwal_App_Data_Sync2</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Sync_Object__c.field-meta.xml
<CustomField>
    <fullName>Sync_Object__c</fullName>
    <label>Sync Object</label>
    <referenceTo>CC_DataSyncObjectMapping__mdt</referenceTo>
    <relationshipLabel>Approval/Amend/Renwal App Data Sync</relationshipLabel>
    <relationshipName>Approval_Amend_Renwal_App_Data_Sync</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/CC_DataSyncFieldMapping__mdt.object-meta.xml
<CustomObject>
    <label>DataSyncFieldMapping</label>
    <pluralLabel>DataSyncFieldMapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_DataSyncObjectMapping__c.field-meta.xml
<CustomField>
    <fullName>CC_DataSyncObjectMapping__c</fullName>
    <description>Object Reference</description>
    <inlineHelpText>Object Reference</inlineHelpText>
    <label>DataSyncObjectMapping</label>
    <referenceTo>CC_DataSyncObjectMapping__mdt</referenceTo>
    <relationshipLabel>DataSyncFieldMapping</relationshipLabel>
    <relationshipName>CC_DataSyncFieldMapping</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Field_Type__c.field-meta.xml
<CustomField>
    <fullName>CC_Field_Type__c</fullName>
    <description>Specify the field type of Target Field</description>
    <inlineHelpText>Specify the field type of Target Field. Only applicable in case of static value or parent relationsip field mapping.
Choose &apos;Expr&apos; if you want to evaluate an expression currently supported expressions are 
Now()
Today()</inlineHelpText>
    <label>Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Expr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>CC_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Mark as Active if available for sync</description>
    <inlineHelpText>Mark as Active if available for sync</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Is_Static_Value__c.field-meta.xml
<CustomField>
    <fullName>CC_Is_Static_Value__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark True: if the value is static and not coming from any field
like always assign &apos;Test&apos; in Description field , 
to do that:
CC_Is_Static_Value =true;
CC_Field_type = Text
CC_Source_Field=Test</description>
    <inlineHelpText>Mark True: if the value is static and not coming from any field
like always assign &apos;Test&apos; in Description field , 
to do that:
CC_Is_Static_Value =true;
CC_Field_type = Text
CC_Source_Field=Test</inlineHelpText>
    <label>Is Static Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Not_for_mapping__c.field-meta.xml
<CustomField>
    <fullName>CC_Not_for_mapping__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Will use this field to only do the query and not do the mapping to the target object</inlineHelpText>
    <label>Not for mapping</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Source_Field__c.field-meta.xml
<CustomField>
    <fullName>CC_Source_Field__c</fullName>
    <description>API name of source field.</description>
    <inlineHelpText>API name of source field.</inlineHelpText>
    <label>Source Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Target_Field__c.field-meta.xml
<CustomField>
    <fullName>CC_Target_Field__c</fullName>
    <description>API name of target field.</description>
    <inlineHelpText>API name of target field.</inlineHelpText>
    <label>Target Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/CC_DataSyncObjectMapping__mdt.object-meta.xml
<CustomObject>
    <description>CC_DataSyncObjectMapping</description>
    <label>DataSyncObjectMapping</label>
    <pluralLabel>CC_DataSyncObjectMapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/fields/CC_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>CC_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>To make sure only active values gets triggered</description>
    <inlineHelpText>Mark as Active if available for sync</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/fields/CC_Relationship_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>CC_Relationship_Api_Name__c</fullName>
    <description>Relationship Api Name (API name of relationship field between source and target object)</description>
    <inlineHelpText>API name of relationship field between source and target object.</inlineHelpText>
    <label>Relationship Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/fields/CC_Source_Object__c.field-meta.xml
<CustomField>
    <fullName>CC_Source_Object__c</fullName>
    <description>API name of source object for data sync.</description>
    <inlineHelpText>API name of source object</inlineHelpText>
    <label>Source Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/fields/CC_Sync_Identifier__c.field-meta.xml
<CustomField>
    <fullName>CC_Sync_Identifier__c</fullName>
    <description>API Name of (date time) field present on target object for storing last sync date/time</description>
    <inlineHelpText>API Name of (date time) field present on target object for storing last sync date/time</inlineHelpText>
    <label>Sync Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/fields/CC_Target_Object__c.field-meta.xml
<CustomField>
    <fullName>CC_Target_Object__c</fullName>
    <description>API Name of target object for data sync.</description>
    <inlineHelpText>API Name of target object</inlineHelpText>
    <label>Target Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/fields/Relationship_Field_in_Apex__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field_in_Apex__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the Relationship Field are mentioned in Apex</description>
    <inlineHelpText>If the Relationship Field are mentioned in Apex</inlineHelpText>
    <label>Relationship Field in Apex</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SyncRecordsOnApproval_BLA.cls
public with sharing class SyncRecordsOnApproval_BLA {
 
    public static void SyncRecordsOnApproval_BLA(String parentObjectName , String applicationType , String flowType,  Set<Id> recordIds ) {

        recordIds = new Set<Id>{'0f0cn000000OyavAAC'};
        String filedApiNameIdentifier = 'Sync_Object_';
        Set<Id> dataSyncRecordsIdForMapping = new Set<Id>();
        String dynamicQuery = '';
        Map<String, Map<String, Object>> metadataMap = new Map<String, Map<String, Object>>();

        List<Approval_Amend_Renwal_App_Data_Sync__mdt > getApprovalSyncMapping = [SELECT Id,DeveloperName,Facility_Application_Type__c,Flow_Type__c,Parent_Object__c,Sync_Object__r.CC_Source_Object__c,Child_Relationship_Field_Name_1__c,Application_Specification_to_Consider__c, 
        Sync_Object_2__r.CC_Source_Object__c,Child_Relationship_Field_Name_2__c,Sync_Object_3__r.CC_Source_Object__c,Child_Relationship_Field_Name_3__c From Approval_Amend_Renwal_App_Data_Sync__mdt where Flow_Type__c =: flowType AND Facility_Application_Type__c =: applicationType AND Parent_Object__c =: parentObjectName ];

        for(Approval_Amend_Renwal_App_Data_Sync__mdt selectedRec : getApprovalSyncMapping){
            Map<String,Object> fieldValue = (Map<String,Object>) JSON.deserializeUntyped(JSON.serialize(selectedRec));// Map if field name and value set eg. {'Sycn_object__c':'ID of CC_DataSyncObjectMapping__mdt'}
            for(String fieldName : fieldValue.keySet()){
                if(fieldName.startsWith(filedApiNameIdentifier) && !(fieldName.endsWith('__r') || fieldName.endsWith('__R') ) ){
                    dataSyncRecordsIdForMapping.add(((ID)fieldValue.get(fieldName)));
                }
            }
        }

        if(!dataSyncRecordsIdForMapping.isEmpty()) {
            List<CC_DataSyncObjectMapping__mdt> getDataSyncMapping = getObjectFieldMappings(dataSyncRecordsIdForMapping);
            metadataMap = processMeatdataRecords(parentObjectName, getDataSyncMapping);
           if(metadataMap != null){
            dynamicQuery = buildDynamicQueryFromMetadata(parentObjectName,metadataMap);
           // system.debug('dynamicQuery ::' + dynamicQuery);
           }
        }
        if(!String.isBlank(dynamicQuery)){
            List<Sobject> recordQueriedData = fetchSourceRecords(dynamicQuery,recordIds);
          //  system.debug('recordQueried ::' + recordQueriedData);
            syncData(recordQueriedData,parentObjectName,metadataMap);
        }

    }

    public static void syncData( List<Sobject> recordQueriedData , String parentObjectName , Map<String, Map<String, Object>> metadataMap){
        List<SObject> parentObjectsToInsert = new List<SObject>();
        List<SObject> recordsToInsert = new List<SObject>();
        Map<String, List<SObject>> childObjectsToInsert = new Map<String, List<SObject>>();
        if (recordQueriedData == null || recordQueriedData.isEmpty()) {
            System.debug('No data to process.');
            return;
        }

        for (SObject record : recordQueriedData) {
          //  System.debug('recordQueriedData :: ' + record);
            parentObjectsToInsert.add(record); 
            for (String relationshipName : metadataMap.keySet()) {
                if (relationshipName != parentObjectName) {
                   // System.debug('relationshipName ::' + relationshipName);
                    List<SObject> childRecords = (List<SObject>) record.getSObjects(relationshipName);
                 //  System.debug('childRecords ::' + childRecords);
                    if (childRecords != null && !childRecords.isEmpty()) {
                        if (!childObjectsToInsert.containsKey(relationshipName)) {
                            childObjectsToInsert.put(relationshipName, new List<SObject>());
                        }
                        childObjectsToInsert.get(relationshipName).addAll(childRecords);
                    }
                }
            }
        }

          // Process and insert parent objects
          if (!parentObjectsToInsert.isEmpty()) {
            recordsToInsert.addAll(prepareParentSobjectRecors(parentObjectsToInsert, metadataMap.get(parentObjectName),parentObjectName));
        }

        // Process and insert child objects
        for (String relationshipName : childObjectsToInsert.keySet()) {
            recordsToInsert.addAll(prepareChildSobjectRecors(childObjectsToInsert.get(relationshipName), metadataMap.get(relationshipName)));
        }
       // system.debug('recordsToInsert :: ' + recordsToInsert);
    }

    public static List<SObject> prepareParentSobjectRecors(List<SObject> records, Map<String, Object> metadata ,String parentObjectName) {
        List<SObject> recordsToInsert = new List<SObject>();
        for (SObject sourceRecord : records) {
            if((String) metadata.get('CC_Source_Object__c') == parentObjectName){
                SObject targetRecord = Schema.getGlobalDescribe().get( (String) metadata.get('CC_Target_Object__c')).newSObject();
                mapSobjectFieldHelper(sourceRecord, targetRecord, metadata);
                recordsToInsert.add(targetRecord);
            }

        }
        return recordsToInsert;
       
    }

    public static List<SObject>  prepareChildSobjectRecors(List<SObject> records, Map<String, Object> metadata ) {
        List<SObject> recordsToInsert = new List<SObject>();
        for (SObject sourceRecord : records) {
            SObject targetRecord = Schema.getGlobalDescribe().get( (String) metadata.get('CC_Target_Object__c')).newSObject();
            mapSobjectFieldHelper(sourceRecord, targetRecord, metadata);
            recordsToInsert.add(targetRecord);
        } 
        return recordsToInsert;
    }

    private static void mapSobjectFieldHelper(SObject sourceRecord, SObject targetRecord, Map<String, Object> metadata) {
        List<Map<String, Object>> fieldMappings = (List<Map<String, Object>>) metadata.get('FieldMappingsDetail');
        if (fieldMappings != null) {
            for (Map<String, Object> fieldMapping : fieldMappings) {
                if((Boolean)  fieldMapping.get('CC_Not_for_mapping__c') == false ){
                    String sourceField = (String) fieldMapping.get('CC_Source_Field__c');
                    String targetField = (String) fieldMapping.get('CC_Target_Field__c');
                   
                        Schema.DisplayType fieldType = getFieldType((String) metadata.get('CC_Target_Object__c'), targetField);
                        if (fieldType == null) {
                            targetRecord.put(targetField, String.valueOf(sourceRecord.get(sourceField))); // Default to String
                            return;
                        }
    
                        try {
                            if(!String.isBlank(String.valueOf(sourceRecord.get(sourceField)))){
                                switch on fieldType {
                                    when DATE {
                                        targetRecord.put(targetField, Date.valueOf(sourceRecord.get(sourceField)));
                                    }
                                    when DATETIME {
                                        targetRecord.put(targetField, DateTime.valueOf(sourceRecord.get(sourceField)));
                                    }
                                    when DOUBLE {
                                        targetRecord.put(targetField, Double.valueOf(sourceRecord.get(sourceField)));
                                    }
                                    when BOOLEAN {
                                        targetRecord.put(targetField, Boolean.valueOf(sourceRecord.get(sourceField)));
                                    }
                                    when TIME {
                                        String[] strTimeSplit = String.valueOf(sourceRecord.get(sourceField)).split(':');
                                        Time timeChange = Time.newInstance( Integer.valueOf(strTimeSplit[0]),Integer.valueOf(strTimeSplit[1]),0 ,0);
                                        targetRecord.put(targetField, timeChange);
                                    } when else {
                                        targetRecord.put(targetField, String.valueOf(sourceRecord.get(sourceField)));
                                    }
                                }
                            }
                         
                        } catch (Exception e) {
                            System.debug('Error setting field ' + targetField + ': ' + e.getMessage());
                            // Handle the exception appropriately (e.g., log, throw a custom exception)
                        }
                    
                  

                   // targetRecord.put(targetField, sourceRecord.get(sourceField));
                }
            }
        }
    }


    private static  List<CC_DataSyncObjectMapping__mdt> getObjectFieldMappings(Set<Id> dataSyncRecordsIdForMapping) {
        Map<String, Map<String, String>> mapping = new Map<String, Map<String, String>>();
        List<CC_DataSyncObjectMapping__mdt> getDataSyncMapping =  [Select id ,CC_Relationship_Api_Name__c,CC_Sync_Identifier__c,CC_Source_Object__c,CC_Target_Object__c,Relationship_Field_in_Apex__c, (select id,CC_Source_Field__c,CC_Target_Field__c,CC_Is_Static_Value__c,CC_Field_Type__c,CC_Not_for_mapping__c  From CC_DataSyncFieldMapping__r where CC_Is_Active__c = true ) 
                                                                   From CC_DataSyncObjectMapping__mdt WHERE Id IN:dataSyncRecordsIdForMapping And CC_Is_Active__c = true With User_Mode Limit 500];
        
        return getDataSyncMapping;
    }

    // Helper to get the child relationship name dynamically
    public static String getChildRelationshipName(String objectName, String childObjectName) {
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        if (schemaMap.containsKey(childObjectName)) {
            List<Schema.ChildRelationship> relationships = Schema.getGlobalDescribe().get(objectName).getDescribe().getChildRelationships();
            for (Schema.ChildRelationship rel : relationships) {
                if (String.valueOf(rel.getChildSObject()) == childObjectName) {
                    return rel.getRelationshipName();
                }
            }
        }
        return null;
    }

     // Helper to get the child relationship name dynamically
     public static  Map<String, Map<String, Object>> processMeatdataRecords(String parentObjectName, List<CC_DataSyncObjectMapping__mdt> getDataSyncMapping ) {
        Map<String, Map<String, Object>> metadataMap = new Map<String, Map<String, Object>>();
       
        for (CC_DataSyncObjectMapping__mdt mappingRecord :getDataSyncMapping) {
            Map<String, Object> objectData = new Map<String, Object>();
            String childRelationshipName = getChildRelationshipName(parentObjectName, mappingRecord.CC_Source_Object__c);
            objectData.put('CC_Source_Object__c',mappingRecord.CC_Source_Object__c);
            objectData.put('CC_Target_Object__c',mappingRecord.CC_Target_Object__c);
            objectData.put('Child_RelationshipName',childRelationshipName);
            // Add child object fields to a list within the inner map.
            List<Map<String, Object>> fieldMappings = new List<Map<String, Object>>();
            for(CC_DataSyncFieldMapping__mdt fieldMapping : mappingRecord.CC_DataSyncFieldMapping__r){
                Map<String, Object> fieldData = new Map<String, Object>();
                fieldData.put('CC_Source_Field__c', fieldMapping.CC_Source_Field__c);
                fieldData.put('CC_Target_Field__c', fieldMapping.CC_Target_Field__c);
                fieldData.put('CC_Not_for_mapping__c', fieldMapping.CC_Not_for_mapping__c);
                fieldData.put('ChildMetadata', fieldMapping);
                fieldMappings.add(fieldData);
            }
            objectData.put('FieldMappingsDetail', fieldMappings);
            if (childRelationshipName != null) {
                metadataMap.put(childRelationshipName, objectData);
            }else if (childRelationshipName == null && mappingRecord.CC_Source_Object__c == parentObjectName) {
                metadataMap.put(parentObjectName, objectData);
            }
           
        }
        return metadataMap;
     }

     public static String buildDynamicQueryFromMetadata(String parentObjectName, Map<String, Map<String, Object>> metadataMap) {
        List<String> selectFields = new List<String>{ 'ID' }; 
         // Add parent object fields
    if (metadataMap.containsKey(parentObjectName)) {
        List<Map<String, Object>> fieldMappings = (List<Map<String, Object>>) metadataMap.get(parentObjectName).get('FieldMappingsDetail');
        if (fieldMappings != null) {
            for (Map<String, Object> fieldMapping : fieldMappings) {
                selectFields.add((String) fieldMapping.get('CC_Source_Field__c'));
            }
        }
    }

    // child object subqueries
    for (String relationshipName : metadataMap.keySet()) {
        if (relationshipName != parentObjectName) {
            Map<String, Object> objectData = metadataMap.get(relationshipName);
            String childRelationshipName = (String) objectData.get('Child_RelationshipName');
            if (childRelationshipName != null) {
                List<Map<String, Object>> childFieldMappings = (List<Map<String, Object>>) objectData.get('FieldMappingsDetail');
                if (childFieldMappings != null && !childFieldMappings.isEmpty()) {
                    Set<String> childFields = new Set<String>(); // Changed to Set from List - to avoid duplicate field names CC_Email__c
                    for (Map<String, Object> fieldMapping : childFieldMappings) {
                            childFields.add((String) fieldMapping.get('CC_Source_Field__c'));
                    }
                    if (!childFields.isEmpty()) {
                        selectFields.add('(SELECT ID, ' + String.join(childFields, ', ') + ' FROM ' + childRelationshipName + ')');
                    }
                }
            }
        }
    }

    String query = 'SELECT ' + String.join(selectFields, ', ') + ' FROM ' + parentObjectName;
    
    return query;
     }

     private static List<SObject> fetchSourceRecords(String query , Set<Id>recordIds){
        query +=  ' WHERE Id IN :recordIds';
        return Database.query(query,AccessLevel.SYSTEM_MODE); 
    }
    
    public static Schema.DisplayType getFieldType(String objectName, String fieldName) {
        SObjectType sObjectType = Schema.getGlobalDescribe().get(objectName);
        if (sObjectType == null) {
            return null; // Or throw an exception
        }
        Map<String, Schema.SObjectField> sObjectFieldMap = sObjectType.getDescribe().fields.getMap();
        if (sObjectFieldMap.containsKey(fieldName)) {
            return sObjectFieldMap.get(fieldName).getDescribe().getType();
        } else {
            return null; // throw an exception: throw new MyCustomException('Field not found: ' + objectName + '.' + fieldName);
        }
    }
}