force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/Approval_Amend_Renwal_App_Data_Sync__mdt.object-meta.xml
<CustomObject>
    <label>Approval/Amend/Renwal App Data Sync</label>
    <pluralLabel>Approval/Amend/Renwal App Data Sync</pluralLabel>
</CustomObject>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Application_Specification_to_Consider__c.field-meta.xml
<CustomField>
    <fullName>Application_Specification_to_Consider__c</fullName>
    <description>List of Application Specification that we need to consider while cloning data to actual records</description>
    <label>Application Specification to Consider</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Child_Relationship_Field_Name_1__c.field-meta.xml
<CustomField>
    <fullName>Child_Relationship_Field_Name_1__c</fullName>
    <label>Child Relationship Field Name 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Child_Relationship_Field_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Child_Relationship_Field_Name_2__c</fullName>
    <label>Child Relationship Field Name 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Child_Relationship_Field_Name_3__c.field-meta.xml
<CustomField>
    <fullName>Child_Relationship_Field_Name_3__c</fullName>
    <label>Child Relationship Field Name 3</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Facility_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Facility_Application_Type__c</fullName>
    <label>Facility/Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Child Care Center</fullName>
                <default>true</default>
                <label>Child Care Center</label>
            </value>
            <value>
                <fullName>Group Home Child Care</fullName>
            </value>
            <value>
                <fullName>Family Home</fullName>
            </value>
            <value>
                <fullName>Friend, Family, Neighbor (FFN) Provider</fullName>
            </value>
            <value>
                <fullName>Relative Care Exempt (RCE) Provider</fullName>
            </value>
            <value>
                <fullName>School Age/ Drop In</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Flow_Type__c.field-meta.xml
<CustomField>
    <fullName>Flow_Type__c</fullName>
    <label>Flow Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <label>Parent Object</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Sync_Object_2__c.field-meta.xml
<CustomField>
    <fullName>Sync_Object_2__c</fullName>
    <label>Sync Object 2</label>
    <referenceTo>CC_DataSyncObjectMapping__mdt</referenceTo>
    <relationshipLabel>Approval/Amend/Renwal App Data Sync (Sync Objects 2)</relationshipLabel>
    <relationshipName>Approval_Amend_Renwal_App_Data_Sync1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Sync_Object_3__c.field-meta.xml
<CustomField>
    <fullName>Sync_Object_3__c</fullName>
    <label>Sync Object 3</label>
    <referenceTo>CC_DataSyncObjectMapping__mdt</referenceTo>
    <relationshipLabel>Approval/Amend/Renwal App Data Sync (Sync Object 3)</relationshipLabel>
    <relationshipName>Approval_Amend_Renwal_App_Data_Sync2</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Approval_Amend_Renwal_App_Data_Sync__mdt/fields/Sync_Object__c.field-meta.xml
<CustomField>
    <fullName>Sync_Object__c</fullName>
    <label>Sync Object</label>
    <referenceTo>CC_DataSyncObjectMapping__mdt</referenceTo>
    <relationshipLabel>Approval/Amend/Renwal App Data Sync</relationshipLabel>
    <relationshipName>Approval_Amend_Renwal_App_Data_Sync</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/BusinessLicenseApplication/fields/CC_Date_of_Inspection_Fire_Marshal__c.field-meta.xml
<CustomField>
    <fullName>CC_Date_of_Inspection_Fire_Marshal__c</fullName>
    <inlineHelpText>Date of Inspection (Fire Marshal Certification)</inlineHelpText>
    <label>Date of Inspection(Fire Marshal)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BusinessLicenseApplication/fields/CC_Date_of_Measurement__c.field-meta.xml
<CustomField>
    <fullName>CC_Date_of_Measurement__c</fullName>
    <label>Date of Measurement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/CC_DataSyncFieldMapping__mdt.object-meta.xml
<CustomObject>
    <label>DataSyncFieldMapping</label>
    <pluralLabel>DataSyncFieldMapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_DataSyncObjectMapping__c.field-meta.xml
<CustomField>
    <fullName>CC_DataSyncObjectMapping__c</fullName>
    <description>Object Reference</description>
    <inlineHelpText>Object Reference</inlineHelpText>
    <label>DataSyncObjectMapping</label>
    <referenceTo>CC_DataSyncObjectMapping__mdt</referenceTo>
    <relationshipLabel>DataSyncFieldMapping</relationshipLabel>
    <relationshipName>CC_DataSyncFieldMapping</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Field_Type__c.field-meta.xml
<CustomField>
    <fullName>CC_Field_Type__c</fullName>
    <description>Specify the field type of Target Field</description>
    <inlineHelpText>Specify the field type of Target Field. Only applicable in case of static value or parent relationsip field mapping.
Choose &apos;Expr&apos; if you want to evaluate an expression currently supported expressions are 
Now()
Today()</inlineHelpText>
    <label>Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Expr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>CC_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Mark as Active if available for sync</description>
    <inlineHelpText>Mark as Active if available for sync</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Is_Static_Value__c.field-meta.xml
<CustomField>
    <fullName>CC_Is_Static_Value__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark True: if the value is static and not coming from any field
like always assign &apos;Test&apos; in Description field , 
to do that:
CC_Is_Static_Value =true;
CC_Field_type = Text
CC_Source_Field=Test</description>
    <inlineHelpText>Mark True: if the value is static and not coming from any field
like always assign &apos;Test&apos; in Description field , 
to do that:
CC_Is_Static_Value =true;
CC_Field_type = Text
CC_Source_Field=Test</inlineHelpText>
    <label>Is Static Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Not_for_mapping__c.field-meta.xml
<CustomField>
    <fullName>CC_Not_for_mapping__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Will use this field to only do the query and not do the mapping to the target object</inlineHelpText>
    <label>Not for mapping</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Source_Field__c.field-meta.xml
<CustomField>
    <fullName>CC_Source_Field__c</fullName>
    <description>API name of source field.</description>
    <inlineHelpText>API name of source field.</inlineHelpText>
    <label>Source Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Target_Field__c.field-meta.xml
<CustomField>
    <fullName>CC_Target_Field__c</fullName>
    <description>API name of target field.</description>
    <inlineHelpText>API name of target field.</inlineHelpText>
    <label>Target Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/CC_DataSyncObjectMapping__mdt.object-meta.xml
<CustomObject>
    <description>CC_DataSyncObjectMapping</description>
    <label>DataSyncObjectMapping</label>
    <pluralLabel>CC_DataSyncObjectMapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/fields/CC_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>CC_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>To make sure only active values gets triggered</description>
    <inlineHelpText>Mark as Active if available for sync</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/fields/CC_Relationship_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>CC_Relationship_Api_Name__c</fullName>
    <description>Relationship Api Name (API name of relationship field between source and target object)</description>
    <inlineHelpText>API name of relationship field between source and target object.</inlineHelpText>
    <label>Relationship Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/fields/CC_Source_Object__c.field-meta.xml
<CustomField>
    <fullName>CC_Source_Object__c</fullName>
    <description>API name of source object for data sync.</description>
    <inlineHelpText>API name of source object</inlineHelpText>
    <label>Source Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/fields/CC_Sync_Identifier__c.field-meta.xml
<CustomField>
    <fullName>CC_Sync_Identifier__c</fullName>
    <description>API Name of (date time) field present on target object for storing last sync date/time</description>
    <inlineHelpText>API Name of (date time) field present on target object for storing last sync date/time</inlineHelpText>
    <label>Sync Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/fields/CC_Target_Object__c.field-meta.xml
<CustomField>
    <fullName>CC_Target_Object__c</fullName>
    <description>API Name of target object for data sync.</description>
    <inlineHelpText>API Name of target object</inlineHelpText>
    <label>Target Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/fields/Relationship_Field_in_Apex__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field_in_Apex__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the Relationship Field are mentioned in Apex</description>
    <inlineHelpText>If the Relationship Field are mentioned in Apex</inlineHelpText>
    <label>Relationship Field in Apex</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SyncRecordsOnApplicationApproval_Copy.cls
public class SyncRecordsOnApplicationApproval_Copy {
    
    public static void handleDataSyncOnApproval(String parentObjectName , String applicationType , String flowType){
        Set<Id> recordIds = new Set<Id>{'0f0cn000000SZfZAAW'};
            Set<Id> dataSyncRecordsIdForMapping = new Set<Id>();
        String filedApiNameIdentifier = 'Sync_Object_';
        Map<String, Map<String, String>> sourceToSource_Target_fieldsMap = new Map<String, Map<String, String>>();//map of <Source Object> , <Source Field, Target Filed> , Eg :  {BusinessLicenseApplication={CC_Date_of_Inspection_Fire_Marshal__c=CC_Date_of_Inspection_Fire_Marshal__c, CC_Date_of_Inspection_Health_Cert__c=CC_Date_of_Inspection_Health_Cert__c, CC_Date_of_Measurement__c=CC_Date_of_Measurement__c}}
        Map<String, CC_DataSyncObjectMapping__mdt> sourceObjToMetadataRecMap = new Map<String, CC_DataSyncObjectMapping__mdt>(); //map of <Source Object> , metadata record
        Map<String,String> sourceObjectToSourceChildRelationshipName = new  Map<String,String>(); // map od source to source child relationship name eg. : {PublicApplicationParticipant  = Applications }
        List<Approval_Amend_Renwal_App_Data_Sync__mdt > getApprovalSyncMapping = [SELECT Id,DeveloperName,Facility_Application_Type__c,Flow_Type__c,Parent_Object__c,Sync_Object__r.CC_Source_Object__c,Child_Relationship_Field_Name_1__c,Application_Specification_to_Consider__c, 
                                                                                  Sync_Object_2__r.CC_Source_Object__c,Child_Relationship_Field_Name_2__c,Sync_Object_3__r.CC_Source_Object__c,Child_Relationship_Field_Name_3__c From Approval_Amend_Renwal_App_Data_Sync__mdt where Flow_Type__c =: flowType AND Facility_Application_Type__c =: applicationType AND Parent_Object__c =: parentObjectName ];
        
        for(Approval_Amend_Renwal_App_Data_Sync__mdt selectedRec : getApprovalSyncMapping){
            Map<String,Object> fieldValue = (Map<String,Object>) JSON.deserializeUntyped(JSON.serialize(selectedRec));// Map if field name and value set eg. {'Sycn_object__c':'ID of CC_DataSyncObjectMapping__mdt'}
            for(String fieldName : fieldValue.keySet()){
                if(fieldName.startsWith(filedApiNameIdentifier) && !(fieldName.endsWith('__r') || fieldName.endsWith('__R') ) ){
                    dataSyncRecordsIdForMapping.add(((ID)fieldValue.get(fieldName)));
                }
            }
        }
        
        //creating map of <Source Object> , <Source Field, Target Filed> , Eg :  {BusinessLicenseApplication={CC_Date_of_Inspection_Fire_Marshal__c=CC_Date_of_Inspection_Fire_Marshal__c, CC_Date_of_Inspection_Health_Cert__c=CC_Date_of_Inspection_Health_Cert__c, CC_Date_of_Measurement__c=CC_Date_of_Measurement__c}}
        if(!dataSyncRecordsIdForMapping.isEmpty()) {
            List<CC_DataSyncObjectMapping__mdt> getDataSyncMapping = getObjectFieldMappings(dataSyncRecordsIdForMapping);
            
            for (CC_DataSyncObjectMapping__mdt mappingRecord :getDataSyncMapping) {
                
                sourceObjToMetadataRecMap.put(mappingRecord.CC_Source_Object__c,mappingRecord );
                
                if(!sourceObjectToSourceChildRelationshipName.containsKey(mappingRecord.CC_Source_Object__c)){
                    String childRelationshipName = (mappingRecord.CC_Source_Object__c == parentObjectName) ? '' : getChildRelationshipName(parentObjectName, mappingRecord.CC_Source_Object__c);
                    sourceObjectToSourceChildRelationshipName.put(mappingRecord.CC_Source_Object__c, childRelationshipName);
                    
                }
                
                if (!sourceToSource_Target_fieldsMap.containsKey(mappingRecord.CC_Source_Object__c)) {
                    sourceToSource_Target_fieldsMap.put(mappingRecord.CC_Source_Object__c, new Map<String, String>());
                }
                
                for(CC_DataSyncFieldMapping__mdt fieldMapping : mappingRecord.CC_DataSyncFieldMapping__r){
                    if(!fieldMapping.CC_Not_for_mapping__c )//need to remove
                        sourceToSource_Target_fieldsMap.get(mappingRecord.CC_Source_Object__c).put(fieldMapping.CC_Source_Field__c, fieldMapping.CC_Target_Field__c);
                }
            }
        }
        System.debug('sourceObjectToSourceChildRelationshipName :: ' + sourceObjectToSourceChildRelationshipName);
        System.debug('sourceObjToMetadataRecMap :: ' + sourceObjToMetadataRecMap);
        System.debug('sourceToSource_Target_fieldsMap :: ' + sourceToSource_Target_fieldsMap);
        String dynamicQuery =  buildDynamicQuery(parentObjectName,sourceToSource_Target_fieldsMap,sourceObjectToSourceChildRelationshipName);
        system.debug('dynamicQuery ::' + dynamicQuery);
        List<Sobject> recordQueriedData = fetchSourceRecords(dynamicQuery,recordIds);
        system.debug('recordQueried ::' + recordQueriedData);
        dataToLoad(parentObjectName,recordQueriedData,sourceToSource_Target_fieldsMap,sourceObjectToSourceChildRelationshipName,sourceObjToMetadataRecMap);
    }
    
    public static String buildDynamicQuery(String parentObjectName, Map<String, Map<String, String>> sourceToSource_Target_fieldsMap , Map<String,String> sourceObjectToSourceChildRelationshipName){
        List<String> selectFields = new List<String>{ 'ID' }; 
            
            // Add parent object fields
            if (sourceToSource_Target_fieldsMap.containsKey(parentObjectName)) {
                for (String parentField : sourceToSource_Target_fieldsMap.get(parentObjectName).keySet()) {
                    selectFields.add(parentField);
                }
            }
        // Add child object subqueries
        for (String childObjectName : sourceObjectToSourceChildRelationshipName.keySet()) {
            if (childObjectName != parentObjectName) {
                String childRelationshipName = sourceObjectToSourceChildRelationshipName.get(childObjectName);
                if (sourceToSource_Target_fieldsMap.containsKey(childObjectName)) {
                    List<String> childFields = new List<String>();
                    for (String childField : sourceToSource_Target_fieldsMap.get(childObjectName).keySet()) {
                        childFields.add(childField);
                    }
                    if (!childFields.isEmpty()) {
                        selectFields.add('(SELECT ID, ' + String.join(childFields, ', ') + ' FROM ' + childRelationshipName + ')');
                    }
                }
            }
        }
        
        String query = 'SELECT ' + String.join(selectFields, ', ') + ' FROM ' + parentObjectName;
        System.debug('query :: ' + query);
        
        return query;
    }
    
    private static List<SObject> fetchSourceRecords(String query , Set<Id>recordIds){
        query +=  ' WHERE Id IN :recordIds';
        return Database.query(query,AccessLevel.SYSTEM_MODE); 
    }
    
    public static void dataToLoad(String parentObjectName, List<Sobject> recordQueriedData, Map<String, Map<String, String>> sourceToSource_Target_fieldsMap , Map<String,String> sourceObjectToSourceChildRelationshipName, Map<String, CC_DataSyncObjectMapping__mdt> sourceObjToMetadataRecMap){
        List<SObject> recordsToUpsert = new List<SObject>();
        String serializedData = JSON.serialize(recordQueriedData);
        system.debug('serializedData :: ' + serializedData);
        List<Object> dataToProcess = (List<Object>) JSON.deserializeUntyped(serializedData);
        for (Object rawRecord : dataToProcess) {
            Map<String, Object> recordData = (Map<String, Object>) rawRecord;
            String parentObject = (String) ((Map<String, Object>) recordData.get('attributes')).get('type');
            
            if(parentObject == parentObjectName){
                // SObjectType accountType = Schema.getGlobalDescribe().get(sourceObjToMetadataRecMap.get(parentObjectName).CC_Target_Object__c);
                //  Map<String,Schema.SObjectField> mfields = accountType.getDescribe().fields.getMap();
                //  Map<String,Schema.SObjectField> sObjectfieldsMap  =  Schema.getGlobalDescribe().get(parentObject).getSobjectType().getDescribe().fields.getMap();
                SObject newRecord = Schema.getGlobalDescribe().get(sourceObjToMetadataRecMap.get(parentObjectName).CC_Target_Object__c).newSObject();
                for(String sourceObjectTargetFileds : sourceToSource_Target_fieldsMap.get(parentObject).keySet()){
                    String targetField = sourceToSource_Target_fieldsMap.get(parentObject).get(sourceObjectTargetFileds);
                    String type_of_field =  getParsedValue(parentObjectName,targetField);
                    if(String.valueOf(recordData.get(sourceObjectTargetFileds)) != null && !String.isBlank(String.valueOf(recordData.get(sourceObjectTargetFileds)))){
                        if(type_of_field == 'DATE'){
                            newRecord.put(targetField, date.valueOf(String.valueOf(recordData.get(sourceObjectTargetFileds))));
                        }else if(type_of_field == 'DATETIME'){
                            newRecord.put(targetField, DateTime.parse(String.valueOf(recordData.get(sourceObjectTargetFileds))));
                        }else if(type_of_field == 'DOUBLE'){
                            newRecord.put(targetField, Double.valueOf(String.valueOf(recordData.get(sourceObjectTargetFileds))));
                        }else if(type_of_field == 'BOOLEAN'){
                            newRecord.put(targetField, Boolean.valueOf(String.valueOf(recordData.get(sourceObjectTargetFileds))));
                        }else{
                            newRecord.put(targetField, String.valueOf(recordData.get(sourceObjectTargetFileds)));
                        }
                    }
                    
                    
                }
                system.debug('newRecord :: ' + newRecord);
                recordsToUpsert.add(newRecord);
            }
        }
        
        //for child processing
        
        for (Object childData : dataToProcess) {
            Map<String, Object> childDataToProcess = (Map<String, Object>) childData;
            for(String childRelationShipName : sourceObjectToSourceChildRelationshipName.keySet()){
                system.debug('childRelationShipName :: ' + childRelationShipName + ' relation name ' + sourceObjectToSourceChildRelationshipName.get(childRelationShipName) + ' containss ' +  childDataToProcess.containsKey(sourceObjectToSourceChildRelationshipName.get(childRelationShipName)));
                if(childDataToProcess.containsKey(sourceObjectToSourceChildRelationshipName.get(childRelationShipName))){
                    Map<String, Object>  childDetails = ( Map<String, Object> )  childDataToProcess.get(sourceObjectToSourceChildRelationshipName.get(childRelationShipName));
                    system.debug('childDetails :: ' + childDetails);
                    if(childDetails != null){
                        List<Object> listOfChildRecord = (List<Object>) childDetails.get('records');
                        for(Object selectedRec : listOfChildRecord){
                            SObject newRecord = Schema.getGlobalDescribe().get(sourceObjToMetadataRecMap.get(childRelationShipName).CC_Target_Object__c).newSObject();
                            Map<String, Object>  records = ( Map<String, Object> ) selectedRec;
                            for(String sourceObjectTargetFileds : sourceToSource_Target_fieldsMap.get(childRelationShipName).keySet()){
                                system.debug('sourceObjectTargetFileds :: ' + sourceObjectTargetFileds);
                                String targetField = sourceToSource_Target_fieldsMap.get(childRelationShipName).get(sourceObjectTargetFileds);
                                system.debug('targetField :: ' + sourceToSource_Target_fieldsMap.get(childRelationShipName).get(sourceObjectTargetFileds));
                                system.debug('sourceObjToMetadataRecMap :: ' + sourceObjToMetadataRecMap.get(childRelationShipName).CC_Target_Object__c);
                                String type_of_field =  getParsedValue(sourceObjToMetadataRecMap.get(childRelationShipName).CC_Target_Object__c,targetField);
                                
                                if(String.valueOf(records.get(sourceObjectTargetFileds)) != null && !String.isBlank(String.valueOf(records.get(sourceObjectTargetFileds)))){
                                    if(type_of_field == 'DATE'){
                                        newRecord.put(targetField, date.valueOf(String.valueOf(records.get(sourceObjectTargetFileds))));
                                    }else if(type_of_field == 'DATETIME'){
                                        newRecord.put(targetField, DateTime.parse(String.valueOf(records.get(sourceObjectTargetFileds))));
                                    }else if(type_of_field == 'DOUBLE'){
                                        newRecord.put(targetField, Double.valueOf(String.valueOf(records.get(sourceObjectTargetFileds))));
                                    }else if(type_of_field == 'BOOLEAN'){
                                        newRecord.put(targetField, Boolean.valueOf(String.valueOf(records.get(sourceObjectTargetFileds))));
                                    }
                                    else if(type_of_field == 'TIME'){
                                        String[] strTimeSplit = String.valueOf(records.get(sourceObjectTargetFileds)).split(':');
                                        Time timeChange = Time.newInstance( Integer.valueOf(strTimeSplit[0]),Integer.valueOf(strTimeSplit[1]),0 ,0);
                                        newRecord.put(targetField,timeChange );
                                    }else{
                                        newRecord.put(targetField, String.valueOf(records.get(sourceObjectTargetFileds)));
                                    }
                                    
                                }
                                
                            }
                            system.debug('newRecord child:: ' + newRecord);
                            if(newRecord != null){
                                recordsToUpsert.add(newRecord);
                            }
                        }
                        
                    }
                }                    
            }
        }
        
        system.debug('newRecord all to upsert:: ' + recordsToUpsert);
    }
    
    private static  List<CC_DataSyncObjectMapping__mdt> getObjectFieldMappings(Set<Id> dataSyncRecordsIdForMapping) {
        Map<String, Map<String, String>> mapping = new Map<String, Map<String, String>>();
        List<CC_DataSyncObjectMapping__mdt> getDataSyncMapping =  [Select id ,CC_Relationship_Api_Name__c,CC_Sync_Identifier__c,CC_Source_Object__c,CC_Target_Object__c,Relationship_Field_in_Apex__c, (select id,CC_Source_Field__c,CC_Target_Field__c,CC_Is_Static_Value__c,CC_Field_Type__c,CC_Not_for_mapping__c  From CC_DataSyncFieldMapping__r where CC_Is_Active__c = true ) 
                                                                   From CC_DataSyncObjectMapping__mdt WHERE Id IN:dataSyncRecordsIdForMapping And CC_Is_Active__c = true With User_Mode Limit 500];
        
        return getDataSyncMapping;
    }
    
    // Helper to get the child relationship name dynamically
    public static String getChildRelationshipName(String objectName, String childObjectName) {
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        if (schemaMap.containsKey(childObjectName)) {
            List<Schema.ChildRelationship> relationships = Schema.getGlobalDescribe().get(objectName).getDescribe().getChildRelationships();
            for (Schema.ChildRelationship rel : relationships) {
                if (String.valueOf(rel.getChildSObject()) == childObjectName) {
                    return rel.getRelationshipName();
                }
            }
        }
        return null;
    }
    
    public static String removeCommaFromSting(String stringWithComma){
        
        if(stringWithComma.endsWith(',')){
            stringWithComma = stringWithComma.substring(0,stringWithComma.length() - 1);
            return stringWithComma;
        }
        return stringWithComma;
    }
    
    public static String getParsedValue(String objectname , String fieldName){
        String type_of_field = '';
        SObjectType accountType = Schema.getGlobalDescribe().get(objectname);
        Map<String,Schema.SObjectField> sObjectfieldsMap = accountType.getDescribe().fields.getMap();
        if(sObjectfieldsMap.containsKey(fieldName)){
            Schema.DescribeFieldResult fieldApi = sObjectfieldsMap.get(fieldName).getDescribe();
            system.debug('fieldApi' + fieldApi);
            system.debug('fieldApi Type' + fieldApi.Type);
            if(fieldApi.Type == schema.DisplayType.DATE){
                // date.parse(String.valueOf(valueToParse));
                type_of_field = 'DATE';
            }
            if(fieldApi.Type == schema.DisplayType.DATETIME){
                // DateTime.parse(String.valueOf(valueToParse));
                type_of_field = 'DATETIME';
            }
            if(fieldApi.Type == schema.DisplayType.DOUBLE){
                // DateTime.parse(String.valueOf(valueToParse));
                type_of_field = 'DOUBLE';
            }
            if(fieldApi.Type == schema.DisplayType.BOOLEAN){
                // DateTime.parse(String.valueOf(valueToParse));
                type_of_field = 'BOOLEAN';
            }
            if(fieldApi.Type == schema.DisplayType.TIME){
                // DateTime.parse(String.valueOf(valueToParse));
                type_of_field = 'TIME';
            }
        }
        
        return type_of_field;
    }
    
    
}