force-app/main/default/objects/CC_DataSyncEvent__e/CC_DataSyncEvent__e.object-meta.xml
<CustomObject>
    <description>It is used to sync data between two objects.</description>
    <label>DataSyncEvent</label>
    <pluralLabel>DataSyncEvent</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_DataSyncEvent__e/fields/CC_Source_Object__c.field-meta.xml
<CustomField>
    <fullName>CC_Source_Object__c</fullName>
    <description>API Name of source Object</description>
    <label>Source Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncEvent__e/fields/CC_Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>CC_Source_Record_Id__c</fullName>
    <description>Source record&apos;s Id.</description>
    <inlineHelpText>Source record&apos;s Id.</inlineHelpText>
    <label>Source Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncEvent__e/fields/CC_Target_Object__c.field-meta.xml
<CustomField>
    <fullName>CC_Target_Object__c</fullName>
    <description>API Name of Target Object</description>
    <label>Target Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncEvent__e/fields/CC_Target_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>CC_Target_Record_Id__c</fullName>
    <description>Id of target record if present else new record will be created</description>
    <inlineHelpText>Id of target record if present else new record will be created</inlineHelpText>
    <label>Target Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CC_DataSyncEventTriggerHelper.cls
/**
 * @description       : 
 * @author            : MTX Group Inc
 * @group             : 
 * @last modified on  : 05-09-2024
 * @last modified by  : MTX Group Inc
**/
public with sharing class CC_DataSyncEventTriggerHelper {

    /**
    * @description : run sync for events assuming all events are having to same Souce and Target Object
    * @author MTX Group Inc | 05-01-2024 
    * @param newEvents 
    **/
    public static void handleDataSync(List<CC_DataSyncEvent__e> newEvents){
        Map<id,String> sourceIdsToTargetIdsMap = new Map<id,String>();
        for(CC_DataSyncEvent__e evt : newEvents){
            sourceIdsToTargetIdsMap.put(evt.CC_Source_Record_Id__c,evt.CC_Target_Record_Id__c);
        }
        CC_DataSyncController dcCtx=new CC_DataSyncController(
            newEvents[0].CC_Source_Object__c,
            newEvents[0].CC_Target_Object__c,
            sourceIdsToTargetIdsMap); 
        dcCtx.execute();
    }
}