force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/CC_DataSyncFieldMapping__mdt.object-meta.xml
<CustomObject>
    <label>DataSyncFieldMapping</label>
    <pluralLabel>DataSyncFieldMapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_DataSyncObjectMapping__c.field-meta.xml
<CustomField>
    <fullName>CC_DataSyncObjectMapping__c</fullName>
    <description>Object Reference</description>
    <inlineHelpText>Object Reference</inlineHelpText>
    <label>DataSyncObjectMapping</label>
    <referenceTo>CC_DataSyncObjectMapping__mdt</referenceTo>
    <relationshipLabel>DataSyncFieldMapping</relationshipLabel>
    <relationshipName>CC_DataSyncFieldMapping</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Field_Type__c.field-meta.xml
<CustomField>
    <fullName>CC_Field_Type__c</fullName>
    <description>Specify the field type of Target Field</description>
    <inlineHelpText>Specify the field type of Target Field. Only applicable in case of static value or parent relationsip field mapping.
Choose &apos;Expr&apos; if you want to evaluate an expression currently supported expressions are 
Now()
Today()</inlineHelpText>
    <label>Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Expr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Is_Static_Value__c.field-meta.xml
<CustomField>
    <fullName>CC_Is_Static_Value__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark True: if the value is static and not coming from any field
like always assign &apos;Test&apos; in Description field , 
to do that:
CC_Is_Static_Value =true;
CC_Field_type = Text
CC_Source_Field=Test</description>
    <inlineHelpText>Mark True: if the value is static and not coming from any field
like always assign &apos;Test&apos; in Description field , 
to do that:
CC_Is_Static_Value =true;
CC_Field_type = Text
CC_Source_Field=Test</inlineHelpText>
    <label>Is Static Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Source_Field__c.field-meta.xml
<CustomField>
    <fullName>CC_Source_Field__c</fullName>
    <description>API name of source field.</description>
    <inlineHelpText>API name of source field.</inlineHelpText>
    <label>Source Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncFieldMapping__mdt/fields/CC_Target_Field__c.field-meta.xml
<CustomField>
    <fullName>CC_Target_Field__c</fullName>
    <description>API name of target field.</description>
    <inlineHelpText>API name of target field.</inlineHelpText>
    <label>Target Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/CC_DataSyncObjectMapping__mdt.object-meta.xml
<CustomObject>
    <description>CC_DataSyncObjectMapping</description>
    <label>DataSyncObjectMapping</label>
    <pluralLabel>CC_DataSyncObjectMapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/fields/CC_Relationship_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>CC_Relationship_Api_Name__c</fullName>
    <description>Relationship Api Name (API name of relationship field between source and target object)</description>
    <inlineHelpText>API name of relationship field between source and target object.</inlineHelpText>
    <label>Relationship Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_DataSyncObjectMapping__mdt/fields/CC_Sync_Identifier__c.field-meta.xml
<CustomField>
    <fullName>CC_Sync_Identifier__c</fullName>
    <description>API Name of (date time) field present on target object for storing last sync date/time</description>
    <inlineHelpText>API Name of (date time) field present on target object for storing last sync date/time</inlineHelpText>
    <label>Sync Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CC_DataSyncController.cls
/**
 * @description       : 
 * @author            : 
 * @group             : 
 * @last modified on  : 02-12-2025
 * @last modified by  : pranay
**/
public with sharing class CC_DataSyncController {
    @TestVisible private String sourceObj;
    @TestVisible private String targetObj;
    @TestVisible private CC_DataSyncObjectMapping__mdt mapping;
    @TestVisible private Map<id,String> sourceToTargetIds = new Map<id,String>();
    @TestVisible private List<SObject> inputData=new List<SObject>();

    public CC_DataSyncController( String sourceObj, String targetObj, Map<id,String> sourceToTargetIds){
        this.sourceObj=sourceObj;
        this.targetObj=targetObj;
        this.mapping=this.fetchMapping();
        this.sourceToTargetIds=sourceToTargetIds;
        this.inputData=this.fetchSourceRecords(sourceToTargetIds.keySet());
    }

    /**
    * @description : fetch FieldMappings
    * @author MTX Group Inc | 05-01-2024 
    * @return CC_DataSyncObjectMapping__mdt 
    **/
    @TestVisible
    private CC_DataSyncObjectMapping__mdt fetchMapping(){
        return CC_CustomMetadataDAO.getDataSyncMapping(this.sourceObj ,this.targetObj)[0];
    }

    /**
    * @description : Fetch all the records with fields to sync
    * @author MTX Group Inc | 05-01-2024 
    * @param recordIds 
    * @return List<SObject> 
    **/
    @TestVisible
    private List<SObject> fetchSourceRecords(set<id> recordIds){
        String selectQuery = 'SELECT Id,';
        for(CC_DataSyncFieldMapping__mdt fieldMapping:this.mapping.CC_DataSyncFieldMapping__r){
            if(fieldMapping.CC_Is_Static_Value__c) {continue;}
            selectQuery += fieldMapping.CC_Source_Field__c + ',';
        }
        selectQuery = selectQuery.removeEnd(',');
        selectQuery += ' FROM ' + this.sourceObj;
        selectQuery += ' WHERE Id IN :recordIds' ;
        return Database.query(selectQuery,AccessLevel.SYSTEM_MODE); // running in system mode as it is invoked by Automated User
    }

    /**
    * @description : Sync the objects and update , if lookup blank then create new Record and update lookup
    * @author MTX Group Inc | 05-01-2024 
    **/
    public void execute(){
        this.syncTarget();
    }

    /**
    * @description Sync the objects and update ,if lookup blank then create new Record
    * @author MTX Group Inc | 05-01-2024 
    * @return List<SObject> 
    **/
    @TestVisible
    private void syncTarget(){
        List<SObject> recToUpsert = new List<SObject>();
        string syncFieldApiName = this.mapping.CC_Sync_Identifier__c;
        for(SObject inp:this.inputData){
            String relationshipName = this.mapping.CC_Relationship_Api_Name__c;
            String targetId = this.sourceToTargetIds.get((id)inp.get('id'));

            Schema.SObjectType objType = Schema.getGlobalDescribe().get(this.targetObj);
            SObject outputObj = objType.newSObject();

            for(CC_DataSyncFieldMapping__mdt fieldMap: this.mapping.CC_DataSyncFieldMapping__r){
                if(fieldMap.CC_Is_Static_Value__c){
                    this.assignStaticValue(fieldMap.CC_Field_Type__c,outputObj,fieldMap);
                }else{
                    if(CC_CommonUtility.getFieldValue(inp,fieldMap.CC_Source_Field__c.split('\\.')) != null )
                    outputObj.put(fieldMap.CC_Target_Field__c,CC_CommonUtility.getFieldValue(inp,fieldMap.CC_Source_Field__c.split('\\.')));
                }
            }
            if(String.isNotBlank(relationshipName) && (inp.get('Id') != null)){ outputObj.put(relationshipName,(string) inp.get('Id')); }
            if(String.isNotBlank(syncFieldApiName)){ outputObj.put(syncFieldApiName,Datetime.now()); }
            if(String.isNotBlank(targetId)) { outputObj.put('id',targetId); }
            recToUpsert.add(outputObj);
        }
        CC_NoSharing_Utility.noSharingUpsert(recToUpsert,true);
    }

    /**
    * @description : if static value then assing value to target field
    * @author MTX Group Inc | 05-15-2024 
    * @param fType 
    * @param outputObj 
    * @param fieldMap 
    **/
    @TestVisible
    private void assignStaticValue(string fType,SObject outputObj,CC_DataSyncFieldMapping__mdt fieldMap ){
        String targetField = fieldMap.CC_Target_Field__c;
        String sourceValue = fieldMap.CC_Source_Field__c;
        if( fType == 'Text'){ outputObj.put(targetField,String.valueOf(sourceValue)); }
        else if(fType == 'Number'){ outputObj.put(targetField,decimal.valueOf(sourceValue));}
        else if(fType == 'Boolean'){ outputObj.put(targetField,Boolean.valueOf(sourceValue)); }
        else if(fType == 'Date'){ outputObj.put(targetField,date.valueOf(sourceValue)); }
        else if(fType == 'DateTime'){ outputObj.put(targetField,dateTime.valueOf(sourceValue)); }
        else if(fType == 'Expr'){
            if(sourceValue.equalsIgnoreCase('Now()')) { outputObj.put(targetField,Datetime.now()); }
            if(sourceValue.equalsIgnoreCase('Today()')) { outputObj.put(targetField,Date.today()); }
        }
    }
}